"DOTAHerononhiddenabilities"
{
	"npc_dota_hero_abaddon"
	{
		"1"					"extended_abaddon_mist_coil"
		"2"					"extended_abaddon_aphotic_shield"
		"3"					"extended_abaddon_curse_of_avernus"
		"4"					"extended_abaddon_over_channel"
		"5"					"extended_abaddon_borrowed_time"
	}

	"npc_dota_hero_alchemist"
	{
		"1"					"extended_alchemist_acid_spray"
		"2"					"extended_alchemist_unstable_concoction"
		"3"					"extended_alchemist_goblins_greed"
		"4"					"extended_alchemist_chemical_rage"
	}

	"npc_dota_hero_ancient_apparition"
	{
		"1"					"ancient_apparition_cold_feet"		
		"2"					"ancient_apparition_ice_vortex"		
		"3"					"ancient_apparition_chilling_touch"	
		"4"					"ancient_apparition_ice_blast"		
	}

	"npc_dota_hero_antimage"
	{
		"1"					"extended_antimage_mana_break"
		"2"					"extended_antimage_blink"
		"3"					"extended_antimage_spell_shield"
		"4"					"extended_antimage_mana_void"
	}

	"npc_dota_hero_arc_warden"
	{
		"1"					"arc_warden_flux"
		"2"					"arc_warden_magnetic_field"
		"3"					"arc_warden_spark_wraith"
		"4"					"arc_warden_tempest_double"
	}

	"npc_dota_hero_axe"
	{
		"1"					"extended_axe_berserkers_call"
		"2"					"extended_axe_battle_hunger"
		"3"					"extended_axe_counter_helix"
		"4"					"extended_axe_culling_blade"
	}

	"npc_dota_hero_bane"
	{
		"1"					"extended_bane_enfeeble"
		"2"					"extended_bane_brain_sap"
		"3"					"extended_bane_nightmare"
		"4"					"extended_bane_nightmare_end"
		"5"					"extended_bane_fiends_grip"
	}

	"npc_dota_hero_batrider"
	{
		"1"					"batrider_sticky_napalm"
		"2"					"batrider_flamebreak"
		"3"					"batrider_firefly"
		"4"					"batrider_flaming_lasso"
	}

	"npc_dota_hero_beastmaster"
	{
		"1"					"beastmaster_wild_axes"
		"2"					"beastmaster_call_of_the_wild"
		"3"					"beastmaster_call_of_the_wild_boar"
		"4"					"beastmaster_inner_beast"
		"5"					"beastmaster_primal_roar"
	}

	"npc_dota_hero_bloodseeker"
	{
		"1"					"extended_bloodseeker_bloodrage"
		"2"					"extended_bloodseeker_blood_bath"
		"3"					"extended_bloodseeker_thirst"
		"4"					"extended_bloodseeker_rupture"
	}

	"npc_dota_hero_bounty_hunter"
	{
		"1"					"extended_bounty_hunter_shuriken_toss"
		"2"					"extended_bounty_hunter_jinada"
		"3"					"extended_bounty_hunter_shadow_walk"
		"4"					"extended_bounty_hunter_headhunter"
		"5"					"extended_bounty_hunter_track"
	}

	"npc_dota_hero_bristleback"
	{
		"1"					"bristleback_viscous_nasal_goo"
		"2"					"bristleback_quill_spray"
		"3"					"bristleback_bristleback"
		"4"					"bristleback_warpath"
	}

	"npc_dota_hero_broodmother"
	{
		"1"					"broodmother_spawn_spiderlings"
		"2"					"broodmother_spin_web"
		"3"					"broodmother_incapacitating_bite"
		"4"					"broodmother_insatiable_hunger"
	}

	"npc_dota_hero_centaur"
	{
		"1"					"extended_centaur_hoof_stomp"
		"2"					"extended_centaur_double_edge"
		"3"					"extended_centaur_return"
		"4"					"extended_centaur_thick_hide"
		"5"					"extended_centaur_stampede"
	}

	"npc_dota_hero_chaos_knight"
	{
		"1"					"chaos_knight_chaos_bolt"
		"2"					"chaos_knight_reality_rift"
		"3"					"chaos_knight_chaos_strike"
		"4"					"chaos_knight_phantasm"
	}

	"npc_dota_hero_chen"
	{
		"1"					"chen_penitence"
		"2"					"chen_test_of_faith"
		"3"					"chen_test_of_faith_teleport"
		"4"					"chen_holy_persuasion"
		"5"					"chen_hand_of_god"
	}

	"npc_dota_hero_clinkz"
	{
		"1"					"extended_clinkz_strafe"
		"2"					"extended_clinkz_searing_arrows"
		"3"					"extended_clinkz_skeleton_walk"
		"4"					"extended_clinkz_death_pact"
	}

	"npc_dota_hero_rattletrap"
	{
		"1"					"rattletrap_battery_assault"
		"2"					"rattletrap_power_cogs"
		"3"					"rattletrap_rocket_flare"
		"4"					"rattletrap_hookshot"
	}   

	"npc_dota_hero_crystal_maiden"
	{
		"1"					"extended_crystal_maiden_crystal_nova"
		"2"					"extended_crystal_maiden_frostbite"
		"3"					"extended_crystal_maiden_brilliance_aura"
		"4"					"extended_crystal_maiden_arcane_dynamo"
		"5"					"extended_crystal_maiden_freezing_field"
	}

	"npc_dota_hero_dark_seer"
	{
		"1"					"dark_seer_vacuum"
		"2"					"dark_seer_ion_shell"
		"3"					"dark_seer_surge"
		"4"					"dark_seer_wall_of_replica"
	}

	"npc_dota_hero_dazzle"
	{
		"1"					"extended_dazzle_poison_touch"
		"2"					"extended_dazzle_shallow_grave"
		"3"					"extended_dazzle_shadow_wave"
		"4"					"extended_dazzle_weave"
	}   

	"npc_dota_hero_death_prophet"
	{
		"1"					"death_prophet_carrion_swarm"
		"2"					"death_prophet_silence"
		"3"					"death_prophet_spirit_siphon"
		"4"					"death_prophet_exorcism"
	}

	"npc_dota_hero_disruptor"
	{
		"1"					"extended_disruptor_thunder_strike"
		"2"					"extended_disruptor_glimpse"
		"3"					"extended_disruptor_kinetic_field"
		"4"					"extended_disruptor_stormbearer"
		"5"					"extended_disruptor_static_storm"
	}

	"npc_dota_hero_doom_bringer"
	{
		"1"					"doom_bringer_devour"
		"2"					"doom_bringer_scorched_earth"
		"3"					"doom_bringer_infernal_blade"
		"6"					"doom_bringer_doom"
	}

	"npc_dota_hero_dragon_knight"
	{
		"1"					"dragon_knight_breathe_fire"
		"2"					"dragon_knight_dragon_tail"
		"3"					"dragon_knight_dragon_blood"
		"4"					"dragon_knight_elder_dragon_form"
	}   

	"npc_dota_hero_drow_ranger"
	{
		"1"					"extended_drow_ranger_frost_arrows"
		"2"					"extended_drow_ranger_gust"
		"3"					"extended_drow_ranger_trueshot"
		"4"					"extended_drow_ranger_deadeye"
		"5"					"extended_drow_ranger_marksmanship"
	}

	"npc_dota_hero_earthshaker"
	{
		"1"					"earthshaker_fissure"
		"2"					"earthshaker_enchant_totem"
		"3"					"earthshaker_aftershock"
		"4"					"earthshaker_echo_slam"
	}

	"npc_dota_hero_earth_spirit"
	{
		"1"					"earth_spirit_boulder_smash"
		"2"					"earth_spirit_rolling_boulder"
		"3"					"earth_spirit_geomagnetic_grip"
		"4"					"earth_spirit_stone_caller"
		"5"					"earth_spirit_magnetize"
	}

	"npc_dota_hero_elder_titan"
	{
		"1"					"elder_titan_echo_stomp"
		"2"					"elder_titan_ancestral_spirit"
		"3"					"elder_titan_natural_order"
		"4"					"elder_titan_earth_splitter"
	}

	"npc_dota_hero_ember_spirit"
	{
		"1"					"ember_spirit_searing_chains"
		"2"					"ember_spirit_sleight_of_fist"
		"3"					"ember_spirit_flame_guard"
		"4"					"ember_spirit_activate_fire_remnant"
		"5"					"ember_spirit_fire_remnant"
	}

	"npc_dota_hero_enchantress"
	{
		"1"					"enchantress_untouchable"
		"2"					"enchantress_enchant"
		"3"					"enchantress_natures_attendants"
		"4"					"enchantress_impetus"
	}

	"npc_dota_hero_enigma"
	{
		"1"					"extended_enigma_malefice"
		"2"					"extended_enigma_demonic_conversion"
		"3"					"extended_enigma_midnight_pulse"
		"4"					"extended_enigma_gravity_well"
		"5"					"extended_enigma_black_hole"
	}

	"npc_dota_hero_faceless_void"
	{
		"1"					"extended_faceless_void_time_walk"
		"2"					"extended_faceless_void_time_dilation"
		"3"					"extended_faceless_void_time_lock"
		"4"					"extended_faceless_void_timelord"
		"5"					"extended_faceless_void_chronosphere"
	}

	"npc_dota_hero_gyrocopter"
	{
		"1"					"gyrocopter_rocket_barrage"
		"2"					"gyrocopter_homing_missile"
		"3"					"gyrocopter_flak_cannon"
		"4"					"gyrocopter_call_down"
	}

	"npc_dota_hero_huskar"
	{
		"1"					"huskar_inner_vitality"
		"2"					"huskar_burning_spear"
		"3"					"huskar_berserkers_blood"
		"4"					"huskar_life_break"
	}

	"npc_dota_hero_invoker"
	{
		"1"					"invoker_quas"
		"2"					"invoker_wex"
		"3"					"invoker_exort"
		"4"					"invoker_invoke"
	}   

	"npc_dota_hero_jakiro"
	{
		"1"					"extended_jakiro_fire_breath"
		"2"					"extended_jakiro_ice_breath"
		"3"					"extended_jakiro_ice_path"
		"4"					"extended_jakiro_liquid_fire"
		"5"					"extended_jakiro_macropyre"
	}

	"npc_dota_hero_juggernaut"
	{
		"1"					"extended_juggernaut_blade_fury"
		"2"					"extended_juggernaut_healing_ward"
		"3"					"extended_juggernaut_blade_dance"
		"4"					"extended_juggernaut_omni_slash"
	}

	"npc_dota_hero_keeper_of_the_light"
	{
		"1"					"keeper_of_the_light_illuminate"
		"2"					"keeper_of_the_light_mana_leak"
		"3"					"keeper_of_the_light_chakra_magic"
		"4"					"keeper_of_the_light_recall"
		"5"					"keeper_of_the_light_blinding_light"
		"6"					"keeper_of_the_light_spirit_form"
	}   

	"npc_dota_hero_kunkka"
	{	
		"1"					"extended_kunkka_torrent"		
		"2"					"extended_kunkka_tidebringer"	
		"3"					"extended_kunkka_x_marks_the_spot"
		"4"					"extended_kunkka_ebb_and_flow"
		"5"					"extended_kunkka_ghostship"
	}

	"npc_dota_hero_legion_commander"
	{
		"1"					"legion_commander_overwhelming_odds"
		"2"					"legion_commander_press_the_attack"
		"3"					"legion_commander_moment_of_courage"
		"4"					"legion_commander_duel"
	}

	"npc_dota_hero_leshrac"
	{
		"1"					"leshrac_split_earth"
		"2"					"leshrac_diabolic_edict"
		"3"					"leshrac_lightning_storm"
		"4"					"leshrac_pulse_nova"
	}

	"npc_dota_hero_lich"
	{
		"1"					"extended_lich_frost_nova"
		"2"					"extended_lich_frost_armor"
		"3"					"extended_lich_dark_ritual"
		"4"					"extended_lich_cold_front"
		"5"					"extended_lich_chain_frost"
	}

	"npc_dota_hero_life_stealer"
	{
		"1"					"life_stealer_rage"
		"2"					"life_stealer_feast"
		"3"					"life_stealer_open_wounds"
		"4"					"life_stealer_infest"
	}   

	"npc_dota_hero_lina"
	{
		"1"					"extended_lina_dragon_slave"
		"2"					"extended_lina_light_strike_array"
		"3"					"extended_lina_fiery_soul"
		"4"					"extended_lina_laguna_blade"
	}

	"npc_dota_hero_lion"
	{
		"1"					"extended_lion_earth_spike"				
		"2"					"extended_lion_hex"				
		"3"					"extended_lion_mana_drain"			
		"4"					"extended_lion_finger_of_death"
	}

	"npc_dota_hero_luna"
	{
		"1"					"luna_lucent_beam"
		"2"					"luna_moon_glaive"
		"3"					"luna_lunar_blessing"
		"4"					"luna_eclipse"
	}

	"npc_dota_hero_lycan"
	{
		"1"					"extended_lycan_summon_wolves"
		"2"					"extended_lycan_howl"
		"3"					"extended_lycan_feral_impulse"
		"4"					"extended_lycan_wolfsbane"
		"5"					"extended_lycan_shapeshift"
	}

	"npc_dota_hero_magnataur"
	{
		"1"					"extended_magnataur_shockwave"
		"2"					"extended_magnataur_empower"
		"3"					"extended_magnataur_skewer"
		"4"					"extended_magnataur_reverse_polarity"
	}

	"npc_dota_hero_medusa"
	{
		"1"					"medusa_split_shot"	
		"2"					"medusa_mystic_snake"		
		"3"					"medusa_mana_shield"
		"4"					"medusa_stone_gaze"
	}

	"npc_dota_hero_meepo"
	{
		"1"					"meepo_earthbind"
		"2"					"meepo_poof"
		"3"					"meepo_geostrike"
		"4"					"meepo_divided_we_stand"
	}   

	"npc_dota_hero_mirana"
	{
		"1"					"extended_mirana_starfall"
		"2"					"extended_mirana_arrow"
		"3"					"extended_mirana_leap"		
		"4"					"extended_mirana_moonlight_shadow"
	}

	"npc_dota_hero_morphling"
	{
		"1"					"morphling_waveform"
		"2"					"morphling_adaptive_strike"
		"3"					"morphling_morph_agi"
		"4"					"morphling_morph_str"
		"5"					"morphling_replicate"
	}

	"npc_dota_hero_monkey_king"
	{
		"1"					"monkey_king_boundless_strike"
		"2"					"monkey_king_tree_dance"
		"3"					"monkey_king_jingu_mastery"
		"4"					"monkey_king_mischief"
		"5"					"monkey_king_wukongs_command"
	}

	"npc_dota_hero_naga_siren"
	{
		"1"					"naga_siren_mirror_image"
		"2"					"naga_siren_ensnare"
		"3"					"naga_siren_rip_tide"
		"4"					"naga_siren_song_of_the_siren"
	}

	"npc_dota_hero_furion"
	{
		"1"					"furion_sprout"
		"2"					"furion_teleportation"
		"3"					"furion_force_of_nature"
		"4"					"furion_wrath_of_nature"
	}

	"npc_dota_hero_necrolyte"
	{
		"1"					"extended_necrolyte_death_pulse"
		"2"					"extended_necrolyte_ghost_shroud"
		"3"					"extended_necrolyte_heartstopper_aura"
		"4"					"extended_necrolyte_sadist"
		"5"					"extended_necrolyte_reapers_scythe"
	}

	"npc_dota_hero_night_stalker"
	{
		"1"					"extended_night_stalker_void"
		"2"					"extended_night_stalker_crippling_fear"
		"3"					"extended_night_stalker_hunter_in_the_night"
		"4"					"extended_night_stalker_stalker_in_the_night"
		"5"					"extended_night_stalker_darkness"
	} 

	"npc_dota_hero_nyx_assassin"
	{
		"1"					"extended_nyx_assassin_impale"
		"2"					"extended_nyx_assassin_mana_burn"
		"3"					"extended_nyx_assassin_spiked_carapace"
		"4"					"extended_nyx_assassin_vendetta"
	}

	"npc_dota_hero_ogre_magi"
	{
		"1"					"ogre_magi_fireblast"
		"2"					"ogre_magi_ignite"
		"3"					"ogre_magi_bloodlust"
		"4"					"ogre_magi_multicast"
	}

	"npc_dota_hero_oracle"
	{
		"1"					"oracle_fortunes_end"
		"2"					"oracle_fates_edict"
		"3"					"oracle_purifying_flames"
		"4"					"oracle_false_promise"
	}

	"npc_dota_hero_obsidian_destroyer"
	{
		"1"					"extended_obsidian_destroyer_arcane_orb"
		"2"					"extended_obsidian_destroyer_astral_imprisonment"
		"3"					"extended_obsidian_destroyer_essence_aura"
		"4"					"extended_obsidian_destroyer_sanity_eclipse"
	}   

	"npc_dota_hero_omniknight"
	{
		"1"					"extended_omniknight_purification"
		"2"					"extended_omniknight_repel"
		"3"					"extended_omniknight_hammer_of_virtue"
		"4"					"extended_omniknight_guardian_angel"
	}   

	"npc_dota_hero_phantom_assassin"
	{
		"1"					"extended_phantom_assassin_stifling_dagger"
		"2"					"extended_phantom_assassin_phantom_strike"
		"3"					"extended_phantom_assassin_blur"
		"4"					"extended_phantom_assassin_coup_de_grace"
	}

	"npc_dota_hero_phantom_lancer"
	{
		"1"					"phantom_lancer_spirit_lance"
		"2"					"phantom_lancer_doppelwalk"
		"3"					"phantom_lancer_phantom_edge"
		"4"					"phantom_lancer_juxtapose"
	}

	"npc_dota_hero_phoenix"
	{
		"1"					"phoenix_icarus_dive"
		"2"					"phoenix_fire_spirits"
		"3"					"phoenix_sun_ray"
		"4"					"phoenix_supernova"
	}

	"npc_dota_hero_puck"
	{
		"1"					"puck_illusory_orb"
		"2"					"puck_waning_rift"
		"3"					"puck_phase_shift"
		"4"					"puck_ethereal_jaunt"
		"5"					"puck_dream_coil"
	}

	"npc_dota_hero_pudge"
	{
		"1"					"extended_pudge_meat_hook"
		"2"					"extended_pudge_rot"
		"3"					"extended_pudge_flesh_heap"
		"4"					"extended_pudge_sharp_hook"
		"5"					"extended_pudge_light_hook"
		"6"					"extended_pudge_dismember"
	}

	"npc_dota_hero_pugna"
	{
		"1"					"extended_pugna_nether_blast"
		"2"					"extended_pugna_decrepify"
		"3"					"extended_pugna_nether_ward"
		"4"					"extended_pugna_life_drain_end"
		"5"					"extended_pugna_life_drain"
	}   

	"npc_dota_hero_queenofpain"
	{
		"1"					"extended_queenofpain_shadow_strike"
		"2"					"extended_queenofpain_blink"
		"3"					"extended_queenofpain_scream_of_pain"
		"4"					"extended_queenofpain_delightful_torment"
		"5"					"extended_queenofpain_sonic_wave"
	}

	"npc_dota_hero_razor"
	{
		"1"					"razor_plasma_field"
		"2"					"razor_static_link"
		"3"					"razor_unstable_current"
		"4"					"razor_eye_of_the_storm"
	}

	"npc_dota_hero_riki"
	{
		"1"					"extended_riki_smoke_screen"
		"2"					"extended_riki_blink_strike"
		"3"					"extended_riki_cloak_and_dagger"
		"4"					"extended_riki_tricks_of_the_trade"
	}

	"npc_dota_hero_rubick"
	{
		"1"					"extended_rubick_telekinesis"
		"2"					"rubick_fade_bolt"
		"3"					"rubick_null_field"
		"4"					"rubick_spell_steal"
	}   

	"npc_dota_hero_sand_king"
	{
		"1"					"extended_sandking_burrowstrike"
		"2"					"extended_sandking_sand_storm"
		"3"					"extended_sandking_caustic_finale"		
		"4"					"extended_sandking_epicenter"
	}

	"npc_dota_hero_shadow_demon"
	{
		"1"					"shadow_demon_disruption"
		"2"					"shadow_demon_soul_catcher"
		"3"					"shadow_demon_shadow_poison"
		"4"					"shadow_demon_demonic_purge"
	}

	"npc_dota_hero_nevermore"
	{
		"1"					"extended_nevermore_shadowraze_close"
		"2"					"extended_nevermore_shadowraze_medium"
		"3"					"extended_nevermore_shadowraze_far"
		"4"					"extended_nevermore_necromastery"
		"5"					"extended_nevermore_dark_lord"
		"6"					"extended_nevermore_requiem"
	}

	"npc_dota_hero_shadow_shaman"
	{
		"1"					"shadow_shaman_ether_shock"
		"2"					"shadow_shaman_voodoo"
		"3"					"shadow_shaman_shackles"
		"4"					"shadow_shaman_mass_serpent_ward"
	}

	"npc_dota_hero_silencer"
	{
		"1"					"extended_silencer_arcane_curse"
		"2"					"extended_silencer_glaives_of_wisdom"
		"3"					"extended_silencer_last_word"
		"4"					"extended_silencer_arcane_supremacy"
		"5"					"extended_silencer_global_silence"
	}

	"npc_dota_hero_skeleton_king"
	{
		"1"					"extended_wraith_king_wraithfire_blast"
		"2"					"extended_wraith_king_vampiric_aura"
		"3"					"extended_wraith_king_mortal_strike"
		"4"					"extended_wraith_king_kingdom_come"
		"5"					"extended_wraith_king_reincarnation"		
	}

	"npc_dota_hero_skywrath_mage"
	{
		"1"					"extended_skywrath_mage_arcane_bolt"
		"2"					"extended_skywrath_mage_concussive_shot"
		"3"					"extended_skywrath_mage_ancient_seal"
		"4"					"extended_skywrath_mage_mystic_flare"
	}

	"npc_dota_hero_slardar"
	{
		"1"					"extended_slardar_guardian_sprint"
		"2"					"extended_slardar_slithereen_crush"
		"3"					"extended_slardar_bash_of_the_deep"
		"4"					"extended_slardar_corrosive_haze"
	}

	"npc_dota_hero_slark"
	{
		"1"					"slark_dark_pact"
		"2"					"slark_pounce"
		"3"					"slark_essence_shift"
		"4"					"slark_shadow_dance"
	}   

	"npc_dota_hero_sniper"
	{
		"1"					"extended_sniper_shrapnel"
		"2"					"extended_sniper_headshot"
		"3"					"extended_sniper_take_aim"		
		"4"					"extended_sniper_assassinate"
	}

	"npc_dota_hero_spectre"
	{
		"1"					"spectre_spectral_dagger"
		"2"					"spectre_desolate"
		"3"					"spectre_dispersion"
		"4"					"spectre_reality"
		"5"					"spectre_haunt"
	}   

	"npc_dota_hero_spirit_breaker"
	{
		"1"					"spirit_breaker_charge_of_darkness"
		"2"					"spirit_breaker_empowering_haste"
		"3"					"spirit_breaker_greater_bash"
		"4"					"spirit_breaker_nether_strike"
	}

	"npc_dota_hero_storm_spirit"
	{
		"1"					"storm_spirit_static_remnant"
		"2"					"storm_spirit_electric_vortex"
		"3"					"storm_spirit_overload"
		"4"					"storm_spirit_ball_lightning"
	}   

	"npc_dota_hero_sven"
	{
		"1"					"extended_sven_storm_bolt"
		"2"					"extended_sven_great_cleave"
		"3"					"extended_sven_warcry"
		"4"					"extended_sven_colossal_slash"
		"5"					"extended_sven_gods_strength"
	}

	"npc_dota_hero_techies"
	{
		"1"					"extended_techies_proximity_mine"
		"2"					"extended_techies_stasis_trap"
		"3"					"extended_techies_blast_off"
		"4"					"extended_techies_focused_detonate"
		"5"					"extended_techies_minefield_sign"
		"6"					"extended_techies_remote_mine"
	}

	"npc_dota_hero_templar_assassin"
	{
		"1"					"templar_assassin_refraction"
		"2"					"templar_assassin_meld"
		"3"					"templar_assassin_psi_blades"
		"4"					"templar_assassin_psionic_trap"
	}

	"npc_dota_hero_terrorblade"
	{
		"1"					"terrorblade_reflection"
		"2"					"terrorblade_conjure_image"
		"3"					"terrorblade_metamorphosis"
		"4"					"terrorblade_sunder"
	}

	"npc_dota_hero_tidehunter"
	{
		"1"					"tidehunter_gush"
		"2"					"tidehunter_kraken_shell"
		"3"					"tidehunter_anchor_smash"
		"4"					"tidehunter_ravage"
	}   

	"npc_dota_hero_tinker"
	{
		"1"					"extended_tinker_laser"
		"2"					"extended_tinker_heat_seeking_missile"
		"3"					"extended_tinker_march_of_the_machines"
		"4"					"extended_tinker_technomancy"
		"5"					"extended_tinker_rearm"
	}

	"npc_dota_hero_shredder"
	{
		"1"					"shredder_whirling_death"
		"2"					"shredder_timber_chain"
		"3"					"shredder_reactive_armor"
		"4"					"shredder_chakram"
	}

	"npc_dota_hero_tiny"
	{
		"1"					"extended_tiny_avalanche"
		"2"					"extended_tiny_toss"
		"3"					"extended_tiny_craggy_exterior"
		"4"					"extended_tiny_rolling_stone"
		"5"					"extended_tiny_grow"		
	}

	"npc_dota_hero_treant"
	{
		"1"					"treant_natures_guise"
		"2"					"treant_leech_seed"
		"3"					"treant_living_armor"
		"4"					"treant_overgrowth"
	}

	"npc_dota_hero_troll_warlord"
	{
		"1"					"extended_troll_warlord_berserkers_rage"
		"2"					"extended_troll_warlord_whirling_axes_melee"
		"3"					"extended_troll_warlord_whirling_axes_ranged"
		"4"					"extended_troll_warlord_fervor"
		"5"					"extended_troll_warlord_battle_trance"
	}

	"npc_dota_hero_tusk"
	{
		"1"					"tusk_ice_shards"
		"2"					"tusk_snowball"
		"3"					"tusk_frozen_sigil"
		"4"					"tusk_walrus_punch"
	}

	"npc_dota_hero_abyssal_underlord"
	{
		"1"					"abyssal_underlord_firestorm"
		"2"					"abyssal_underlord_pit_of_malice"
		"3"					"abyssal_underlord_atrophy_aura"
		"4"					"abyssal_underlord_dark_rift"
	}

	"npc_dota_hero_undying"
	{
		"1"					"undying_decay"
		"2"					"undying_soul_rip"
		"3"					"undying_tombstone"
		"4"					"undying_flesh_golem"
	}

	"npc_dota_hero_ursa"
	{
		"1"					"extended_ursa_earthshock"
		"2"					"extended_ursa_overpower"
		"3"					"extended_ursa_fury_swipes"
		"4"					"extended_ursa_territorial_hunter"
		"5"					"extended_ursa_enrage"
	}

	"npc_dota_hero_viper"
	{
		"1"					"viper_poison_attack"
		"2"					"viper_nethertoxin"
		"3"					"viper_corrosive_skin"
		"4"					"viper_viper_strike"
	}

	"npc_dota_hero_vengefulspirit"
	{
		"1"					"extended_vengefulspirit_magic_missile"
		"2"					"extended_vengefulspirit_wave_of_terror"
		"3"					"extended_vengefulspirit_command_aura"
		"4"					"extended_vengefulspirit_rancor"
		"5"					"extended_vengefulspirit_swap_back"
		"6"					"extended_vengefulspirit_nether_swap"
	}   

	"npc_dota_hero_venomancer"
	{
		"1"					"extended_venomancer_venomous_gale"
		"2"					"extended_venomancer_poison_sting"
		"3"					"extended_venomancer_plague_ward"
		"4"					"extended_venomancer_toxicity"
		"5"					"extended_venomancer_poison_nova"
	}   

	"npc_dota_hero_visage"
	{
		"1"					"visage_grave_chill"
		"2"					"visage_soul_assumption"
		"3"					"visage_gravekeepers_cloak"
		"4"					"visage_summon_familiars"
	}

	"npc_dota_hero_warlock"
	{
		"1"					"extended_warlock_fatal_bonds"
		"2"					"extended_warlock_shadow_word"
		"3"					"extended_warlock_upheaval"
		"4"					"extended_warlock_rain_of_chaos"
	}

	"npc_dota_hero_weaver"
	{
		"1"					"weaver_the_swarm"
		"2"					"weaver_shukuchi"
		"3"					"weaver_geminate_attack"
		"4"					"weaver_time_lapse"
	}

	"npc_dota_hero_windrunner"
	{
		"1"					"windrunner_shackleshot"
		"2"					"windrunner_powershot"
		"3"					"windrunner_windrun"
		"4"					"windrunner_focusfire"
	}

	"npc_dota_hero_winter_wyvern"
	{
		"1"					"winter_wyvern_arctic_burn"
		"2"					"winter_wyvern_splinter_blast"
		"3"					"winter_wyvern_cold_embrace"
		"4"					"winter_wyvern_winters_curse"
	}   

	"npc_dota_hero_wisp"
	{
		"1"					"wisp_tether"
		"2"					"wisp_spirits"
		"3"					"wisp_overcharge"
		"4"					"wisp_relocate"
	}

	"npc_dota_hero_witch_doctor"
	{
		"1"					"extended_witch_doctor_paralyzing_cask"
		"2"					"extended_witch_doctor_voodoo_restoration"
		"3"					"extended_witch_doctor_maledict"
		"4"					"extended_witch_doctor_death_ward"
	}

	"npc_dota_hero_zuus"
	{
		"1"					"zuus_arc_lightning"
		"2"					"zuus_lightning_bolt"
		"3"					"zuus_static_field"
		"4"					"zuus_thundergods_wrath"
	}
}